# Copyright 2026 Aleksei Aleinikov
# SPDX-License-Identifier: Apache-2.0

"""Docker-based multi-node testbed generator for IPv8 networks.

Generates Dockerfiles, docker-compose.yml, and per-node configuration
files for running multi-node IPv8 topologies in isolated containers.

Each node runs as a separate container with its own IPv8 address,
route table, and optional services (router, NAT, flow collector, etc.).

Usage::

    tb = Testbed(name="demo")
    tb.add_node(NodeSpec(name="r1", address="64496-10.0.1.1", role=NodeRole.ROUTER))
    tb.add_node(NodeSpec(name="h1", address="64496-10.0.1.10", role=NodeRole.HOST,
                         gateway="r1"))
    tb.add_link("r1", "h1", network="10.0.1.0/24")
    compose = tb.generate_compose()
    tb.write_output("/tmp/testbed")
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path

import yaml


# ---------------------------------------------------------------------------
# Node roles
# ---------------------------------------------------------------------------


class NodeRole(str, Enum):
    """Role of a node in the testbed."""

    HOST = "host"
    ROUTER = "router"
    NAT_GATEWAY = "nat_gateway"
    COLLECTOR = "collector"


# ---------------------------------------------------------------------------
# Node specification
# ---------------------------------------------------------------------------


@dataclass(slots=True)
class NodeSpec:
    """Specification for a single testbed node (container)."""

    name: str
    address: str  # IPv8 address string
    role: NodeRole = NodeRole.HOST
    gateway: str = ""  # name of default gateway node
    routes: list[dict[str, str]] = field(default_factory=list)
    services: list[str] = field(default_factory=list)
    environment: dict[str, str] = field(default_factory=dict)
    command: str = ""

    def to_dict(self) -> dict[str, object]:
        return {
            "name": self.name,
            "address": self.address,
            "role": self.role.value,
            "gateway": self.gateway,
            "routes": self.routes,
            "services": self.services,
            "environment": dict(self.environment),
            "command": self.command,
        }


# ---------------------------------------------------------------------------
# Link specification
# ---------------------------------------------------------------------------


@dataclass(slots=True)
class LinkSpec:
    """A network link between two nodes."""

    node_a: str
    node_b: str
    network: str  # Docker network CIDR
    network_name: str = ""
    latency_ms: int = 0
    bandwidth_mbps: int = 0

    def __post_init__(self) -> None:
        if not self.network_name:
            self.network_name = f"net-{self.node_a}-{self.node_b}"

    def to_dict(self) -> dict[str, object]:
        return {
            "node_a": self.node_a,
            "node_b": self.node_b,
            "network": self.network,
            "network_name": self.network_name,
            "latency_ms": self.latency_ms,
            "bandwidth_mbps": self.bandwidth_mbps,
        }


# ---------------------------------------------------------------------------
# Testbed stats
# ---------------------------------------------------------------------------


@dataclass(slots=True)
class TestbedStats:
    """Summary statistics for a testbed."""

    node_count: int = 0
    link_count: int = 0
    network_count: int = 0
    router_count: int = 0
    host_count: int = 0

    def to_dict(self) -> dict[str, int]:
        return {
            "node_count": self.node_count,
            "link_count": self.link_count,
            "network_count": self.network_count,
            "router_count": self.router_count,
            "host_count": self.host_count,
        }


# ---------------------------------------------------------------------------
# Dockerfile generation
# ---------------------------------------------------------------------------

DOCKERFILE_TEMPLATE = """\
# Auto-generated by ipv8lab docker testbed
FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml .
COPY src/ src/

RUN pip install --no-cache-dir -e .

COPY configs/ /app/configs/

ENTRYPOINT ["ipv8lab"]
"""


def generate_dockerfile(base_image: str = "python:3.11-slim") -> str:
    """Generate Dockerfile content for a testbed node."""
    return DOCKERFILE_TEMPLATE.replace("python:3.11-slim", base_image)


# ---------------------------------------------------------------------------
# Topology presets
# ---------------------------------------------------------------------------


def build_two_asn_topology(
    asn_a: int = 64496,
    asn_b: int = 64497,
    hosts_per_asn: int = 2,
) -> tuple[list[NodeSpec], list[LinkSpec]]:
    """Build a two-ASN topology with border routers and hosts.

    Returns (nodes, links).
    """
    nodes: list[NodeSpec] = []
    links: list[LinkSpec] = []

    # Border routers
    r1 = NodeSpec(
        name=f"r1-as{asn_a}",
        address=f"{asn_a}.10.0.1.1",
        role=NodeRole.ROUTER,
    )
    r2 = NodeSpec(
        name=f"r2-as{asn_b}",
        address=f"{asn_b}.10.0.1.1",
        role=NodeRole.ROUTER,
    )
    nodes.extend([r1, r2])

    # Inter-AS link
    links.append(LinkSpec(
        node_a=r1.name, node_b=r2.name,
        network="172.16.0.0/30",
        network_name="backbone",
    ))

    # Hosts
    for i in range(1, hosts_per_asn + 1):
        h_a = NodeSpec(
            name=f"h{i}-as{asn_a}",
            address=f"{asn_a}.10.0.1.{10 + i}",
            role=NodeRole.HOST,
            gateway=r1.name,
        )
        h_b = NodeSpec(
            name=f"h{i}-as{asn_b}",
            address=f"{asn_b}.10.0.1.{10 + i}",
            role=NodeRole.HOST,
            gateway=r2.name,
        )
        nodes.extend([h_a, h_b])
        links.append(LinkSpec(
            node_a=r1.name, node_b=h_a.name,
            network=f"10.{asn_a % 256}.{i}.0/24",
            network_name=f"lan-as{asn_a}-{i}",
        ))
        links.append(LinkSpec(
            node_a=r2.name, node_b=h_b.name,
            network=f"10.{asn_b % 256}.{i}.0/24",
            network_name=f"lan-as{asn_b}-{i}",
        ))

    return nodes, links


def build_star_topology(
    center_name: str = "core",
    center_asn: int = 64496,
    spoke_count: int = 4,
) -> tuple[list[NodeSpec], list[LinkSpec]]:
    """Build a star topology with a central router and spoke hosts."""
    nodes: list[NodeSpec] = []
    links: list[LinkSpec] = []

    core = NodeSpec(
        name=center_name,
        address=f"{center_asn}.10.0.0.1",
        role=NodeRole.ROUTER,
    )
    nodes.append(core)

    for i in range(1, spoke_count + 1):
        host = NodeSpec(
            name=f"spoke-{i}",
            address=f"{center_asn}.10.0.{i}.10",
            role=NodeRole.HOST,
            gateway=center_name,
        )
        nodes.append(host)
        links.append(LinkSpec(
            node_a=center_name, node_b=host.name,
            network=f"10.0.{i}.0/24",
            network_name=f"spoke-net-{i}",
        ))

    return nodes, links


def build_mesh_topology(
    node_count: int = 4,
    asn: int = 64496,
) -> tuple[list[NodeSpec], list[LinkSpec]]:
    """Build a full mesh of routers."""
    nodes: list[NodeSpec] = []
    links: list[LinkSpec] = []

    for i in range(1, node_count + 1):
        r = NodeSpec(
            name=f"mesh-{i}",
            address=f"{asn}.10.0.{i}.1",
            role=NodeRole.ROUTER,
        )
        nodes.append(r)

    # Full mesh links
    for i in range(len(nodes)):
        for j in range(i + 1, len(nodes)):
            links.append(LinkSpec(
                node_a=nodes[i].name,
                node_b=nodes[j].name,
                network=f"172.16.{i}.{j * 4}/30",
                network_name=f"mesh-{i + 1}-{j + 1}",
            ))

    return nodes, links


# ---------------------------------------------------------------------------
# Testbed
# ---------------------------------------------------------------------------


class Testbed:
    """Docker-based multi-node IPv8 testbed.

    Manages node specifications, links, and generates Docker Compose
    configurations for deploying multi-node topologies.
    """

    def __init__(self, name: str = "ipv8-testbed") -> None:
        self._name = name
        self._nodes: dict[str, NodeSpec] = {}
        self._links: list[LinkSpec] = []

    # ---- properties ----

    @property
    def name(self) -> str:
        return self._name

    @property
    def node_count(self) -> int:
        return len(self._nodes)

    @property
    def link_count(self) -> int:
        return len(self._links)

    # ---- building ----

    def add_node(self, spec: NodeSpec) -> None:
        """Add a node to the testbed."""
        self._nodes[spec.name] = spec

    def add_link(
        self,
        node_a: str,
        node_b: str,
        network: str,
        *,
        network_name: str = "",
        latency_ms: int = 0,
        bandwidth_mbps: int = 0,
    ) -> LinkSpec:
        """Add a network link between two nodes."""
        link = LinkSpec(
            node_a=node_a, node_b=node_b,
            network=network, network_name=network_name,
            latency_ms=latency_ms, bandwidth_mbps=bandwidth_mbps,
        )
        self._links.append(link)
        return link

    def load_topology(
        self,
        nodes: list[NodeSpec],
        links: list[LinkSpec],
    ) -> None:
        """Load a pre-built topology."""
        for n in nodes:
            self._nodes[n.name] = n
        self._links.extend(links)

    # ---- generation ----

    def generate_compose(self) -> dict[str, object]:
        """Generate a docker-compose.yml structure."""
        services: dict[str, object] = {}
        networks: dict[str, object] = {}

        # Collect networks from links
        for link in self._links:
            net_cfg: dict[str, object] = {
                "driver": "bridge",
                "ipam": {
                    "config": [{"subnet": link.network}],
                },
            }
            networks[link.network_name] = net_cfg

        # Build services
        for name, node in self._nodes.items():
            svc: dict[str, object] = {
                "build": {"context": ".", "dockerfile": "Dockerfile"},
                "container_name": f"{self._name}-{name}",
                "hostname": name,
                "environment": {
                    "IPV8_NODE_NAME": name,
                    "IPV8_ADDRESS": node.address,
                    "IPV8_ROLE": node.role.value,
                    **node.environment,
                },
                "cap_add": ["NET_ADMIN"],
            }

            if node.gateway:
                svc["environment"]["IPV8_GATEWAY"] = node.gateway  # type: ignore[index]

            # Attach to networks
            node_networks: dict[str, object] = {}
            for link in self._links:
                if name in (link.node_a, link.node_b):
                    node_networks[link.network_name] = {}
            if node_networks:
                svc["networks"] = node_networks

            # Command
            if node.command:
                svc["command"] = node.command
            elif node.role == NodeRole.ROUTER:
                svc["command"] = "route simulate --config /app/configs/${IPV8_NODE_NAME}.yaml"
            else:
                svc["command"] = "udp run --config /app/configs/${IPV8_NODE_NAME}.yaml"

            services[name] = svc

        compose: dict[str, object] = {
            "version": "3.8",
            "services": services,
            "networks": networks,
        }
        return compose

    def generate_compose_yaml(self) -> str:
        """Generate docker-compose.yml as YAML string."""
        return yaml.dump(
            self.generate_compose(),
            default_flow_style=False,
            sort_keys=False,
        )

    def generate_node_config(self, name: str) -> dict[str, object]:
        """Generate per-node YAML configuration."""
        node = self._nodes.get(name)
        if node is None:
            raise ValueError(f"Unknown node: {name}")

        config: dict[str, object] = {
            "name": name,
            "address": node.address,
            "role": node.role.value,
        }

        if node.gateway:
            config["gateway"] = node.gateway

        if node.routes:
            config["routes"] = node.routes

        # Add peers (connected nodes)
        peers: list[str] = []
        for link in self._links:
            if link.node_a == name:
                peers.append(link.node_b)
            elif link.node_b == name:
                peers.append(link.node_a)
        config["peers"] = peers

        return config

    def write_output(self, output_dir: str) -> list[str]:
        """Write all generated files to output directory.

        Returns list of created file paths.
        """
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        configs_dir = out / "configs"
        configs_dir.mkdir(exist_ok=True)

        created: list[str] = []

        # Dockerfile
        dockerfile_path = out / "Dockerfile"
        dockerfile_path.write_text(generate_dockerfile())
        created.append(str(dockerfile_path))

        # docker-compose.yml
        compose_path = out / "docker-compose.yml"
        compose_path.write_text(self.generate_compose_yaml())
        created.append(str(compose_path))

        # Per-node configs
        for name in self._nodes:
            cfg_path = configs_dir / f"{name}.yaml"
            cfg = self.generate_node_config(name)
            cfg_path.write_text(yaml.dump(cfg, default_flow_style=False, sort_keys=False))
            created.append(str(cfg_path))

        return created

    # ---- queries ----

    def get_node(self, name: str) -> NodeSpec | None:
        return self._nodes.get(name)

    def get_nodes(self) -> list[NodeSpec]:
        return list(self._nodes.values())

    def get_links(self) -> list[LinkSpec]:
        return list(self._links)

    def stats(self) -> TestbedStats:
        routers = sum(1 for n in self._nodes.values() if n.role == NodeRole.ROUTER)
        hosts = sum(1 for n in self._nodes.values() if n.role == NodeRole.HOST)
        net_names = {link.network_name for link in self._links}
        return TestbedStats(
            node_count=len(self._nodes),
            link_count=len(self._links),
            network_count=len(net_names),
            router_count=routers,
            host_count=hosts,
        )

    def to_dict(self) -> dict[str, object]:
        return {
            "name": self._name,
            "stats": self.stats().to_dict(),
            "nodes": [n.to_dict() for n in self._nodes.values()],
            "links": [lk.to_dict() for lk in self._links],
        }

    def clear(self) -> None:
        self._nodes.clear()
        self._links.clear()
